### PR TITLE
Delete works on payment type ticket 8

### PR DESCRIPTION
**Pull request by Downeastrussell**
Test
-delete a payment type

if you have a completed order with a paymentTypeId then it should throw an error if you try to delete that Payment Type
 order.paymentTypeId == PaymentType.Id

ALSO!!
-added GET all products-view-index as the home page(A page that shows all things for sale)
-added a search bar on the "Home Page" 

test
-type in a city to search for products by city.

### CODE REVIEW

**Comment by MattRowee** [comment]
Works as described. Need Order component to delete completed orders and test that functionality?

Regardless 🐗 👨‍💻  (boar coder) Excellent job

**Comment by MattRowee** [comment]
🔪 🏙

**Review by MattRowee — COMMENTED** [review]
Heck yeah

**Comment by iamnickmitchell** [comment]
👍 Looks good! 🚀 👨

**Pull request merged**
